version: "3.8"
services:
  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'ecotrack'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ecotrackadmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ecotrackpassword1330'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ecotrackpassword1330'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
  
networks: 
  internal-network:
    driver: bridge
    name: ecotrack
volumes:
  db:
    driver: local