version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.3
    
    ports:
      - 5432:5432
    volumes:
      - C:/EcoTrackPostgresDatabase:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mert2004
      - POSTGRES_USER=root
      - POSTGRES_DB=ecotrack
