import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../../providers/Providers";
import SidebarProviderSupervizor from "./components/SidebarProviderSupervizor";
import WrapperProvider from "./workers-performance-analysis-charts/WrapperProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <WrapperProvider>

        <Providers>


          
          <div className="relative w-full h-fit flex flex-row max-xl:flex-col max-xl:p-0  justify-between  items-start  bg-[#14213f] ">
            <SidebarProviderSupervizor >{children}</SidebarProviderSupervizor>
          </div>
        </Providers>
      </WrapperProvider>

      </body>
    </html>
  );
}
