import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../../providers/Providers";
import Sidebar from "../../components/Sidebar";
import SidebarProvider from "../../components/SidebarProvider";
import SidebarProviderSupervizor from "./components/SidebarProviderSupervizor";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

          
          <div className="relative w-full h-fit flex flex-row max-xl:flex-col max-xl:p-0  justify-between  items-start  bg-[#14213f] ">
            <SidebarProviderSupervizor >{children}</SidebarProviderSupervizor>
          </div>

        </Providers>
      </body>
    </html>
  );
}
