qlogging:
  level:
    org:
      springframework:
        security=DEBUG:
api:
  prefix: /api/v1
spring:
  application:
    name: EcoTrack
  datasource:
    url: jdbc:postgresql://localhost:5432/ecotrack
    username: root
    password: mert2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql


