import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../../providers/Providers";
import SidebarProvider from "../../components/SidebarProvider";
import UserActivityDetector from "./sensors/[id]/components/UserActivityDetector";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
          const session = cookies().get("session")?.value

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <UserActivityDetector session = {session}/>
          <div className="relative w-full h-fit flex flex-row max-xl:flex-col max-xl:p-0  justify-between  items-start  bg-[#14213f] min-h-screen">
            <SidebarProvider >{children}</SidebarProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
